let myAge = 25;
let earlyYears = 2;
earlyYears *= 10.5;
let laterYears = myAge - 2;
laterYears *= 4;
console.log(earlyYears);
console.log(laterYears);
let myAgeInDogYears = earlyYears + laterYears;
let myName = "Levi" .toLowerCase();
console.log(`My name is ${myName}. I am ${myAge} old in human years, which is ${myAgeInDogYears} old in dog years.`);